"""
Enhanced Audit and Reporting System for the Personal AI Employee
Generates comprehensive weekly CEO briefings with accounting integration
"""

import os
import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Any, Optional
from collections import defaultdict
import pandas as pd
import logging

from base_watcher import BaseWatcher


class AuditSystem:
    """System for auditing business activities and generating CEO briefings"""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.logger = logging.getLogger(self.__class__.__name__)
        self.briefings_path = self.vault_path / "Business_Reports" / "Briefings"
        self.briefings_path.mkdir(parents=True, exist_ok=True)

    def generate_weekly_ceo_briefing(self) -> str:
        """Generate the comprehensive weekly CEO briefing with accounting data"""
        # Calculate the week range (Sunday to Saturday)
        today = datetime.now()
        start_of_week = today - timedelta(days=today.weekday() + 1)  # Last Sunday
        end_of_week = start_of_week + timedelta(days=6)  # Following Saturday

        # Format dates for filename
        week_start_str = start_of_week.strftime("%Y-%m-%d")
        week_end_str = end_of_week.strftime("%Y-%m-%d")

        # Generate the briefing content
        briefing_content = self._generate_briefing_content(start_of_week, end_of_week)

        # Write to file
        briefing_filename = f"{week_start_str}_Weekly_CEO_Briefing.md"
        briefing_path = self.briefings_path / briefing_filename

        briefing_path.write_text(briefing_content)

        self.logger.info(f"Weekly CEO briefing generated: {briefing_path}")
        return str(briefing_path)

    def _generate_briefing_content(self, start_date: datetime, end_date: datetime) -> str:
        """Generate the content for the CEO briefing"""
        # Get all the data for the briefing
        revenue_data = self._get_revenue_data(start_date, end_date)
        completed_tasks = self._get_completed_tasks(start_date, end_date)
        bottlenecks = self._get_bottlenecks(start_date, end_date)
        accounting_summary = self._get_accounting_summary(start_date, end_date)
        proactive_suggestions = self._get_proactive_suggestions()

        # Calculate week number and year
        week_num = start_date.isocalendar()[1]
        year = start_date.year

        content = f"""---
generated: {datetime.now().isoformat()}
period: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}
week: {year}-W{week_num:02d}
---

# Weekly CEO Briefing - Week {week_num} of {year}

## Executive Summary
{self._generate_executive_summary(revenue_data, completed_tasks, bottlenecks)}

## Revenue Analysis
### This Week
- **Total Revenue:** ${revenue_data['total_revenue']:,.2f}
- **Number of Transactions:** {revenue_data['transaction_count']}
- **Average Transaction Value:** ${revenue_data['avg_transaction_value']:,.2f}

### Monthly Progress
- **Monthly Target:** ${revenue_data['monthly_target']:,.2f}
- **Current MTD:** ${revenue_data['current_mtd']:,.2f}
- **Progress to Target:** {revenue_data['progress_to_target']:.1f}%

### Top Revenue Sources
{self._format_revenue_sources(revenue_data['top_sources'])}

## Completed Tasks
{self._format_completed_tasks(completed_tasks)}

## Bottlenecks & Issues
{self._format_bottlenecks(bottlenecks)}

## Accounting Summary
{self._format_accounting_summary(accounting_summary)}

## Proactive Suggestions
{self._format_proactive_suggestions(proactive_suggestions)}

## Upcoming Deadlines
{self._get_upcoming_deadlines()}

---

*Generated by AI Employee vGold.1 at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

        return content

    def _generate_executive_summary(self, revenue_data: Dict, completed_tasks: List, bottlenecks: List) -> str:
        """Generate the executive summary based on available data"""
        if bottlenecks:
            return f"**Mixed week** with {len(completed_tasks)} tasks completed but {len(bottlenecks)} identified bottlenecks. Revenue at ${revenue_data['total_revenue']:,.2f}."
        elif revenue_data['total_revenue'] >= revenue_data['weekly_target']:
            return f"**Strong week** with {len(completed_tasks)} tasks completed and ${revenue_data['total_revenue']:,.2f} in revenue."
        else:
            return f"**Steady week** with {len(completed_tasks)} tasks completed and ${revenue_data['total_revenue']:,.2f} in revenue. {len(bottlenecks)} issues identified."

    def _get_revenue_data(self, start_date: datetime, end_date: datetime) -> Dict:
        """Get revenue data for the specified period"""
        # Default values
        revenue_data = {
            'total_revenue': 0.0,
            'transaction_count': 0,
            'avg_transaction_value': 0.0,
            'monthly_target': 10000.0,  # Default from Business_Goals.md
            'current_mtd': 0.0,
            'progress_to_target': 0.0,
            'weekly_target': 2500.0,  # 1/4 of monthly target
            'top_sources': {}
        }

        # Try to read Business_Goals.md to get actual targets
        business_goals_path = self.vault_path / "Business_Goals.md"
        if business_goals_path.exists():
            try:
                content = business_goals_path.read_text()
                # This would parse the Business_Goals.md file to extract actual targets
                # For now, we'll use default values
                pass
            except Exception as e:
                self.logger.warning(f"Could not read Business_Goals.md: {e}")

        # Get accounting data from Done folder (simulated accounting entries)
        done_path = self.vault_path / "Done"
        if done_path.exists():
            for file_path in done_path.glob("*.md"):
                content = file_path.read_text()
                # Look for payment/invoice related keywords in completed tasks
                if any(keyword in content.lower() for keyword in ['payment', 'invoice', 'paid', 'received']):
                    # Simulated revenue tracking (in a real system, this would come from actual accounting data)
                    # For now, we'll just estimate based on common patterns
                    if 'payment' in content.lower() or 'invoice' in content.lower():
                        # Extract amount from content if possible (simplified)
                        revenue_data['total_revenue'] += 500.0  # Simulated value
                        revenue_data['transaction_count'] += 1

        # Calculate average transaction value
        if revenue_data['transaction_count'] > 0:
            revenue_data['avg_transaction_value'] = revenue_data['total_revenue'] / revenue_data['transaction_count']

        # Calculate progress to target
        revenue_data['current_mtd'] = revenue_data['total_revenue']  # Simplified
        if revenue_data['monthly_target'] > 0:
            revenue_data['progress_to_target'] = (revenue_data['current_mtd'] / revenue_data['monthly_target']) * 100

        return revenue_data

    def _get_completed_tasks(self, start_date: datetime, end_date: datetime) -> List[Dict]:
        """Get completed tasks from the Done folder"""
        completed_tasks = []
        done_path = self.vault_path / "Done"

        if done_path.exists():
            for file_path in done_path.glob("*.md"):
                try:
                    # Try to get the creation/modification date from the filename or content
                    file_stat = file_path.stat()
                    file_date = datetime.fromtimestamp(file_stat.st_mtime)

                    # Check if the file was modified within our date range
                    if start_date <= file_date.date() <= end_date.date():
                        content = file_path.read_text()
                        # Extract task summary from the file content
                        first_line = content.split('\n')[0] if content else file_path.stem
                        completed_tasks.append({
                            'title': first_line.replace('#', '').strip(),
                            'filename': file_path.name,
                            'completed_date': file_date.isoformat()
                        })
                except Exception as e:
                    self.logger.error(f"Error reading completed task {file_path}: {e}")

        return completed_tasks[:20]  # Limit to 20 most recent

    def _get_bottlenecks(self, start_date: datetime, end_date: datetime) -> List[Dict]:
        """Get identified bottlenecks from the system"""
        bottlenecks = []

        # Check for tasks that took longer than expected
        plans_path = self.vault_path / "Plans"
        if plans_path.exists():
            for file_path in plans_path.glob("*.md"):
                try:
                    content = file_path.read_text()
                    # Look for signs of task delays or issues
                    if any(keyword in content.lower() for keyword in ['delay', 'blocked', 'stuck', 'waiting']):
                        bottlenecks.append({
                            'task': file_path.stem,
                            'issue': 'Task appears to be delayed or blocked based on plan status',
                            'file': str(file_path)
                        })
                except Exception as e:
                    self.logger.error(f"Error reading plan {file_path}: {e}")

        # Check for approval requests that are pending too long
        pending_approval_path = self.vault_path / "Pending_Approval"
        if pending_approval_path.exists():
            for file_path in pending_approval_path.glob("*.md"):
                try:
                    file_stat = file_path.stat()
                    file_age = datetime.now() - datetime.fromtimestamp(file_stat.st_ctime)

                    # If approval has been pending for more than 2 days, flag as bottleneck
                    if file_age.days > 2:
                        bottlenecks.append({
                            'task': file_path.stem,
                            'issue': f'Approval pending for {file_age.days} days',
                            'file': str(file_path)
                        })
                except Exception as e:
                    self.logger.error(f"Error checking approval age {file_path}: {e}")

        return bottlenecks[:10]  # Limit to 10 most significant

    def _get_accounting_summary(self, start_date: datetime, end_date: datetime) -> Dict:
        """Get accounting data from integrated systems (simulated)"""
        # In a real implementation, this would connect to the Odoo MCP server
        # For now, we'll provide a simulated summary based on available data

        accounting_summary = {
            'total_revenue': 0,
            'total_expenses': 0,
            'net_income': 0,
            'outstanding_invoices': 0,
            'paid_invoices': 0,
            'total_customers': 0,
            'new_customers': 0
        }

        # Look for accounting-related files in the vault
        for folder_name in ['Accounting', 'Done', 'Plans', 'Needs_Action']:
            folder_path = self.vault_path / folder_name
            if folder_path.exists():
                for file_path in folder_path.glob("*.md"):
                    content = file_path.read_text().lower()
                    if any(keyword in content for keyword in ['invoice', 'payment', 'customer', 'expense']):
                        # Simulated accounting data extraction
                        if 'invoice' in content and 'sent' in content:
                            accounting_summary['total_revenue'] += 1000
                            accounting_summary['outstanding_invoices'] += 1
                        elif 'payment' in content and 'received' in content:
                            accounting_summary['paid_invoices'] += 1
                            accounting_summary['total_revenue'] += 1000

        accounting_summary['total_expenses'] = accounting_summary['total_revenue'] * 0.3  # Simulated
        accounting_summary['net_income'] = accounting_summary['total_revenue'] - accounting_summary['total_expenses']

        return accounting_summary

    def _get_proactive_suggestions(self) -> List[Dict]:
        """Get proactive suggestions based on system analysis"""
        suggestions = []

        # Check for potential cost optimization opportunities
        self._check_cost_optimization(suggestions)

        # Check for process improvements
        self._check_process_improvements(suggestions)

        # Check for business opportunities
        self._check_business_opportunities(suggestions)

        return suggestions[:5]  # Limit to 5 suggestions

    def _check_cost_optimization(self, suggestions: List[Dict]):
        """Check for potential cost optimization opportunities"""
        # Look for recurring expenses or subscriptions
        logs_path = self.vault_path / "Logs"
        if logs_path.exists():
            for file_path in logs_path.glob("*.md"):
                content = file_path.read_text()
                # This would analyze logs for recurring expenses
                # For now, a placeholder check
                if 'subscription' in content.lower() or 'monthly' in content.lower():
                    suggestions.append({
                        'category': 'Cost Optimization',
                        'suggestion': f'Review {file_path.stem} for potential cost optimization',
                        'confidence': 'medium'
                    })

    def _check_process_improvements(self, suggestions: List[Dict]):
        """Check for potential process improvements"""
        # Analyze task completion times and patterns
        needs_action_path = self.vault_path / "Needs_Action"
        if needs_action_path.exists():
            for file_path in needs_action_path.glob("*.md"):
                content = file_path.read_text()
                # Look for patterns that might indicate process improvements
                if 'repeat' in content.lower() or 'again' in content.lower():
                    suggestions.append({
                        'category': 'Process Improvement',
                        'suggestion': f'Consider automating repetitive task in {file_path.stem}',
                        'confidence': 'high'
                    })

    def _check_business_opportunities(self, suggestions: List[Dict]):
        """Check for potential business opportunities"""
        # Look for customer engagement or business development opportunities
        inbox_path = self.vault_path / "Inbox"
        if inbox_path.exists():
            for file_path in inbox_path.glob("*.md"):
                content = file_path.read_text()
                if any(keyword in content.lower() for keyword in ['interested', 'potential', 'opportunity', 'new']):
                    suggestions.append({
                        'category': 'Business Opportunity',
                        'suggestion': f'Follow up on potential opportunity in {file_path.stem}',
                        'confidence': 'high'
                    })

    def _format_revenue_sources(self, sources: Dict) -> str:
        """Format the revenue sources for the briefing"""
        if not sources:
            return "- No specific revenue sources identified"

        lines = []
        for source, amount in list(sources.items())[:5]:  # Top 5 sources
            lines.append(f"- **{source}**: ${amount:,.2f}")

        return '\n'.join(lines) if lines else "- No specific revenue sources identified"

    def _format_completed_tasks(self, tasks: List[Dict]) -> str:
        """Format the completed tasks for the briefing"""
        if not tasks:
            return "No tasks completed this week.\n\n"

        lines = ["### Tasks Completed\n"]
        for task in tasks:
            lines.append(f"- [{task['title']}]({task['filename']}) - {task['completed_date'][:10]}")

        return '\n'.join(lines) + "\n"

    def _format_bottlenecks(self, bottlenecks: List[Dict]) -> str:
        """Format the bottlenecks for the briefing"""
        if not bottlenecks:
            return "No significant bottlenecks identified.\n\n"

        lines = ["### Identified Bottlenecks\n"]
        lines.append("| Task | Issue | File |\n|------|-------|------|")

        for bottleneck in bottlenecks:
            file_name = Path(bottleneck['file']).name
            lines.append(f"| {bottleneck['task']} | {bottleneck['issue']} | [{file_name}]({file_name}) |")

        return '\n'.join(lines) + "\n"

    def _format_accounting_summary(self, summary: Dict) -> str:
        """Format the accounting summary for the briefing"""
        return f"""
### Financial Summary
- **Total Revenue:** ${summary['total_revenue']:,.2f}
- **Total Expenses:** ${summary['total_expenses']:,.2f}
- **Net Income:** ${summary['net_income']:,.2f}
- **Outstanding Invoices:** {summary['outstanding_invoices']}
- **Paid Invoices:** {summary['paid_invoices']}
- **Total Customers:** {summary['total_customers']}
- **New Customers:** {summary['new_customers']}
"""

    def _format_proactive_suggestions(self, suggestions: List[Dict]) -> str:
        """Format the proactive suggestions for the briefing"""
        if not suggestions:
            return "No proactive suggestions at this time.\n\n"

        lines = []
        for suggestion in suggestions:
            lines.append(f"#### {suggestion['category']}")
            lines.append(f"- {suggestion['suggestion']} *(Confidence: {suggestion['confidence']})*\n")

        return '\n'.join(lines)

    def _get_upcoming_deadlines(self) -> str:
        """Get upcoming deadlines and important dates"""
        # Check Business_Goals.md for project deadlines
        business_goals_path = self.vault_path / "Business_Goals.md"
        deadlines = []

        if business_goals_path.exists():
            content = business_goals_path.read_text()
            # Look for due dates in the business goals
            import re
            # Find patterns like "Due Mar 31", "Due April 30", etc.
            date_patterns = [
                r'Due\s+(\w+\s+\d+)',  # Due Mar 31
                r'Due\s+(\d+/\d+)',    # Due 03/31
                r'Due\s+(\d{4}-\d{2}-\d{2})'  # Due 2023-03-31
            ]

            for pattern in date_patterns:
                matches = re.findall(pattern, content, re.IGNORECASE)
                for match in matches:
                    try:
                        # Attempt to parse the date
                        if '/' in match:
                            deadline_date = datetime.strptime(match, '%m/%d')
                            deadline_date = deadline_date.replace(year=datetime.now().year)
                        elif '-' in match:
                            deadline_date = datetime.strptime(match, '%Y-%m-%d')
                        else:
                            # Month day format like "Mar 31"
                            deadline_date = datetime.strptime(f"{match} {datetime.now().year}", '%b %d %Y')

                        # Only include deadlines within the next 30 days
                        if 0 <= (deadline_date - datetime.now()).days <= 30:
                            deadlines.append({
                                'event': f'Project deadline',
                                'date': deadline_date.strftime('%Y-%m-%d'),
                                'days_until': (deadline_date - datetime.now()).days
                            })
                    except:
                        continue

        if not deadlines:
            return "No upcoming deadlines identified in the next 30 days.\n\n"

        lines = ["### Upcoming Deadlines\n"]
        for deadline in deadlines:
            lines.append(f"- **{deadline['event']}**: {deadline['date']} ({deadline['days_until']} days)")

        return '\n'.join(lines) + "\n"

    def generate_accounting_audit(self, start_date: datetime, end_date: datetime) -> str:
        """Generate a detailed accounting audit report"""
        # This would integrate with the Odoo MCP server in a real implementation
        # For now, we'll create a template report

        report_path = self.vault_path / "Accounting" / f"audit_{start_date.strftime('%Y%m%d')}_{end_date.strftime('%Y%m%d')}.md"

        report_content = f"""---
generated: {datetime.now().isoformat()}
period: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}
type: accounting_audit
---

# Accounting Audit Report
**Period:** {start_date.strftime('%B %d, %Y')} to {end_date.strftime('%B %d, %Y')}

## Summary
- Total Revenue: $0.00
- Total Expenses: $0.00
- Net Income: $0.00
- Transactions Processed: 0
- Outstanding Invoices: 0
- Paid Invoices: 0

## Revenue by Category
| Category | Amount |
|----------|--------|
| Services | $0.00 |
| Products | $0.00 |

## Expenses by Category
| Category | Amount |
|----------|--------|
| Operations | $0.00 |
| Marketing | $0.00 |
| Tools & Software | $0.00 |

## Customer Analysis
- New Customers: 0
- Total Customers: 0
- Average Revenue per Customer: $0.00

## Compliance Check
- All transactions properly recorded: Unknown
- Tax obligations met: Unknown
- Financial reporting status: Not integrated

*Note: This report requires integration with accounting system (Odoo) for accurate data.*

---
*Generated by AI Employee Audit System at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(report_content)

        return str(report_path)


class AuditLoggingSystem:
    """System for comprehensive audit logging"""

    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.logs_path = self.vault_path / "Logs"
        self.logs_path.mkdir(exist_ok=True)

        # Set up Python logging
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(self.logs_path / f"audit_{datetime.now().strftime('%Y%m%d')}.log"),
                logging.StreamHandler()
            ]
        )
        self.logger = logging.getLogger(self.__class__.__name__)

    def log_action(self, action_type: str, actor: str, target: str, parameters: Dict[str, Any],
                   approval_status: str = "auto", approved_by: str = "system", result: str = "success"):
        """Log an action performed by the AI Employee"""
        log_entry = {
            "timestamp": datetime.now().isoformat(),
            "action_type": action_type,
            "actor": actor,
            "target": target,
            "parameters": parameters,
            "approval_status": approval_status,
            "approved_by": approved_by,
            "result": result
        }

        # Write to JSON log file
        log_file = self.logs_path / f"actions_{datetime.now().strftime('%Y%m%d')}.json"
        try:
            # Read existing logs if file exists
            if log_file.exists():
                with open(log_file, 'r') as f:
                    existing_logs = json.load(f)
            else:
                existing_logs = []
        except json.JSONDecodeError:
            existing_logs = []

        # Append new log and write back
        existing_logs.append(log_entry)
        with open(log_file, 'w') as f:
            json.dump(existing_logs, f, indent=2)

        # Also write a markdown summary
        self._write_markdown_log_summary(log_entry)

    def _write_markdown_log_summary(self, log_entry: Dict[str, Any]):
        """Write a markdown summary of the action log"""
        summary_file = self.logs_path / f"actions_{datetime.now().strftime('%Y%m%d')}.md"
        summary_content = f"""
## Action Log - {datetime.now().strftime('%Y-%m-%d')}

**Timestamp:** {log_entry['timestamp']}
**Action Type:** {log_entry['action_type']}
**Actor:** {log_entry['actor']}
**Target:** {log_entry['target']}
**Parameters:** {json.dumps(log_entry['parameters'], indent=2)}
**Approval Status:** {log_entry['approval_status']}
**Approved By:** {log_entry['approved_by']}
**Result:** {log_entry['result']}

---
"""

        # Append to the markdown file
        with open(summary_file, 'a') as f:
            f.write(summary_content)


if __name__ == "__main__":
    # Example usage
    import argparse

    parser = argparse.ArgumentParser(description='Audit and Reporting System for AI Employee')
    parser.add_argument('--vault-path', type=str, required=True, help='Path to the Obsidian vault')
    args = parser.parse_args()

    audit_system = AuditSystem(vault_path=args.vault_path)
    briefing_path = audit_system.generate_weekly_ceo_briefing()
    print(f"Generated CEO briefing: {briefing_path}")